### PR TITLE
DM-30773: Add warnings about user-added datasets in the butler repo

### PR DESCRIPTION
**Pull request by hsinfang**

### CODE REVIEW

**Comment by hsinfang** [comment]
@MelissaGraham  @leannep  please review. 
The statement on not restoring any user-added data is somewhat strong, but I prefer to be explicit upfront.  

At the moment, there is a chance for delegates to mess up each other's user-added datasets inside the butler repo. It should be rare but it's not impossible in scenarios such as not following our pipetask collection naming convention, accessing the postgres directly against our advice, malicious behaviors,  software bugs, and so on.   

In the future the new butler client/server shall solve these issues but it won't happen this year. 

We'd like to know how important this is from CET's point of view.  Would you be okay if we just say "no user data is backed up" during DP0 era?   Currently we aren't able to restore the butler repo back to a previous state.  There are things we might do to mitigate but it's unlikely to be ready this month and it will cost money.

**Comment by MelissaGraham** [comment]
Thank you!! I think strong statements are preferred, to give as clear an idea of the expectations and risks as possible. 

General statements like "no user data is backed up" seem appropriate to me. And to also follow that up with more specific statements for users who would wonder about such things would also be good (maybe with a bit more info to describe some of the terms that would be new to people, like postgres). 

To explicitly say what the postgres-related advice is would be good too. In short, a little bit of redundancy in this page is OK (or rearranging of the sections, maybe the risks should go from major to minor instead of being categorized?).

@hsinfang anything else you'd like to add to this branch at this time or shall I merge?

**Review by MelissaGraham — APPROVED** [review]

**Comment by hsinfang** [comment]
Thank you @MelissaGraham.  Actually the term "postgres" isn't directly used in the write up, and I think that's good, as delegates should not need to know what the backend database is.  I mentioned it in the comment just to give some examples why we have concerns. But hopefully no delegates will even think about it at all.   I added one more sentence about butler (https://github.com/lsst/dp0-1_lsst_io/commit/d3f1a7abe936cae05eb38a718d2bdcf49e3489df) 


Note that this is only about the user-added data _inside the butler repo_. It's not a statement about user data in general.

**Comment by hsinfang** [comment]
And I asked a few questions in https://github.com/lsst/dp0-1_lsst_io/commit/ccb298cff99587ad7aa22478b311a437c52b5c72  

Otherwise, yes, please merge if you think this is fine to merge.

**Pull request merged**
